### ISSUE TITLE
File issues for each item in the Feedback Received section of the explainer

### ISSUE THREAD

**Issue by hober** [privacycg/is-logged-in#1]
There are [a number of open IsLoggedIn issues](https://github.com/webkit/explainers/issues?q=is%3Aissue+is%3Aopen+label%3AIsLoggedIn) in the [WebKit/explainers repo](https://github.com/webkit/explainers/). Please triage them and port them over here.

**Comment by johnwilander** [comment]
I have now triaged and ported the relevant issues from the WebKit repo to here. I think we should also file the items in the "Feedback Received" section of the explainer as issues and then remove that section.

**Comment by hober** [comment]
> I have now triaged and ported the relevant issues from the WebKit repo to here. I think we should also file the items in the "Feedback Received" section of the explainer as issues and then remove that section.

Okay; I've retitled this bug to match the remaining task.

**Comment by johnwilander** [comment]
I have now filed issues for the previous feedback. I did not file for "Websites May Not Like Managed Logins" because I think it's captured in the discussion of non-mediated logins and I didn't file for "Successful Logins Hard to Detect" since IsLoggedIn comes down to a website claim anyway and so it's up to the website to ensure that the login was successful before setting the status.
